spring.datasource.url: ${DATABASE_URL}
spring.datasource.username: ${DATABASE_USERNAME}
spring.datasource.password: ${DATABASE_PASSWORD}
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.hibernate.ddl-auto: none
spring.datasource.hikari.maxLifeTime: 60000
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
server.port: ${PORT:8080}

spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:/db.changelog\changelog-master.xml
spring.jackson.serialization-inclusion: non_null

